language: objective-c

osx_image: xcode7.1
xcode_project: appledoc.xcodeproj
xcode_scheme: appledoc
xcode_sdk: macosx10.11

before_script:
- gem install xcpretty

script:
- set -o pipefail && xcodebuild -project appledoc.xcodeproj -scheme appledoc test | xcpretty
